# Generated by Django 3.1.7 on 2021-03-30 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title_ru', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('content_uz', models.TextField(blank=True, null=True)),
                ('content_ru', models.TextField(blank=True, default=None, null=True)),
                ('content_en', models.TextField(blank=True, default=None, null=True)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('post_added', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, default='download.jpeg', height_field='img_h', null=True, upload_to=main.models.convert_fn, width_field='img_w')),
                ('img_w', models.IntegerField(default=0)),
                ('img_h', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
