# Generated by Django 3.1.4 on 2020-12-08 09:45

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201208_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='not_found.png', height_field='img_h', null=True, upload_to=main.models.convert_fn, width_field='img_w'),
        ),
    ]
