# Generated by Django 3.1.7 on 2021-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210331_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
