# Generated by Django 3.1.7 on 2021-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201208_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
