# Generated by Django 3.1.7 on 2021-03-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210310_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
